spring.application.name=BioProject

spring.datasource.url=jdbc:mysql://localhost:3306/bioproject
spring.datasource.username=root
spring.datasource.password=buz67vdN!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#loads mock data
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=true
